# Generated by Django 4.0.3 on 2022-04-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_tripcategorypax_alter_tripprice_cadpax'),
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryPax',
        ),
    ]
