# Generated by Django 4.0.3 on 2022-07-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Package_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrive', models.DateField(verbose_name='Data da Chegada')),
                ('date_departure', models.DateField(verbose_name='Data da Partida')),
                ('num_adults', models.IntegerField(verbose_name='Quantidade adultos')),
                ('num_child', models.IntegerField(verbose_name='Quantidade crianças')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.destiny', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
            },
        ),
        migrations.CreateModel(
            name='Data_Customer_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Seu nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail para contato')),
                ('phonenumber', models.CharField(max_length=13, verbose_name='Telefone para contato')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='package.data_package_one')),
            ],
            options={
                'verbose_name': 'Dados do cliente para pacote',
                'verbose_name_plural': 'Dados do cliente para pacote',
            },
        ),
        migrations.CreateModel(
            name='Child_Package_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_age', models.CharField(blank=True, max_length=2, null=True, verbose_name='')),
                ('data_package_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.data_package_one')),
            ],
            options={
                'verbose_name': 'Idade da criança',
                'verbose_name_plural': 'Idade das crianças',
            },
        ),
    ]
