# Generated by Django 4.0 on 2022-09-13 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destiny', '0001_initial'),
        ('trip', '0002_alter_activity_catpax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrive', models.DateField(default='01/01/2022', verbose_name='Data da Chegada')),
                ('date_departure', models.DateField(default='01/12/2022', verbose_name='Data da Partida')),
                ('num_adults', models.IntegerField(default=2, verbose_name='Quantidade adultos')),
                ('num_child', models.IntegerField(default=0, verbose_name='Quantidade crianças')),
                ('name', models.CharField(max_length=200, verbose_name='Seu nome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail para contato')),
                ('phonenumber', models.CharField(max_length=15, verbose_name='Telefone para contato')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.destiny', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
            },
        ),
        migrations.CreateModel(
            name='PackageTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.activityprice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
            options={
                'verbose_name': 'Atividade do pacote',
                'verbose_name_plural': 'Atividades do Pacote',
            },
        ),
        migrations.CreateModel(
            name='Child_Package_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_age', models.CharField(blank=True, max_length=2, null=True, verbose_name='')),
                ('data_package_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
            options={
                'verbose_name': 'Idade da criança',
                'verbose_name_plural': 'Idade das crianças',
            },
        ),
    ]
