# Generated by Django 4.0.3 on 2022-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetrips',
            name='catpax',
        ),
        migrations.RemoveField(
            model_name='packagetrips',
            name='price',
        ),
        migrations.AlterField(
            model_name='child_package_one',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='date_arrive',
            field=models.DateField(default='01/01/2023', verbose_name='Data da Chegada'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='date_departure',
            field=models.DateField(default='01/12/2023', verbose_name='Data da Partida'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='phonenumber',
            field=models.CharField(max_length=15, verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='packagetrips',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
