# Generated by Django 4.0.3 on 2022-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child_package_one',
            options={'verbose_name': 'Idade da criança', 'verbose_name_plural': 'Idade das crianças'},
        ),
        migrations.AlterField(
            model_name='child_package_one',
            name='children_age',
            field=models.CharField(blank=True, max_length=2, verbose_name=''),
        ),
    ]
