# Generated by Django 4.0.3 on 2022-06-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child_package_one',
            old_name='children_age',
            new_name='children_age0',
        ),
    ]
