# Generated by Django 4.0.3 on 2022-07-20 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_package_one',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='data_package_one',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='data_package_one',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='E-mail para contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_package_one',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Seu nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_package_one',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, verbose_name='Telefone para contato'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Data_Customer_Package',
        ),
    ]
