# Generated by Django 4.0.3 on 2022-07-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_child_package_one_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_package_one',
            name='children_age',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name=''),
        ),
    ]
