# Generated by Django 4.0.3 on 2022-08-16 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_data_package_one_date_arrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_package_one',
            name='date_arrive',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Chegada'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='date_departure',
            field=models.DateField(default='31/12/2023', verbose_name='Data da Partida'),
        ),
    ]
