# Generated by Django 4.0.3 on 2022-06-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_rename_children_age_child_package_one_children_age0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child_package_one',
            old_name='children_age0',
            new_name='children_age',
        ),
    ]
