# Generated by Django 4.0.3 on 2022-08-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_remove_packagetrips_catpax_remove_packagetrips_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetrips',
            options={'verbose_name': 'Atividade do pacote', 'verbose_name_plural': 'Atividades do Pacote'},
        ),
    ]
