# Generated by Django 4.0.3 on 2022-08-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_activity_catpax'),
        ('package', '0003_alter_data_package_one_date_arrive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catpax', models.CharField(max_length=255, verbose_name='CatPax')),
                ('price', models.CharField(max_length=255, verbose_name='Preço')),
                ('id_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.activityprice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.data_package_one')),
            ],
        ),
        migrations.DeleteModel(
            name='Chosen_Package',
        ),
    ]
