# Generated by Django 4.0.3 on 2022-06-29 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
        ('package', '0003_rename_children_age0_child_package_one_children_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child_package_one',
            old_name='Data_package_one',
            new_name='data_package_one',
        ),
        migrations.AlterField(
            model_name='child_package_one',
            name='children_age',
            field=models.CharField(max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.destiny', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='num_adults',
            field=models.IntegerField(verbose_name='Quantidade adultos'),
        ),
        migrations.AlterField(
            model_name='data_package_one',
            name='num_child',
            field=models.IntegerField(verbose_name='Quantidade crianças'),
        ),
    ]
