# Generated by Django 4.0.3 on 2022-07-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_child_package_one_children_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Customer_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Seu nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail para contato')),
                ('phoneNumber', models.CharField(max_length=13, verbose_name='Telefone para contato')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='package.data_package_one')),
            ],
            options={
                'verbose_name': 'Dados do cliente para pacote',
                'verbose_name_plural': 'Dados do cliente para pacote',
            },
        ),
    ]
