# Generated by Django 4.0.3 on 2022-07-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_data_customer_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_customer_package',
            name='phoneNumber',
        ),
    ]
