# Generated by Django 4.0.3 on 2022-07-16 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_remove_data_customer_package_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_customer_package',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, verbose_name='Telefone para contato'),
            preserve_default=False,
        ),
    ]
