# Generated by Django 4.0 on 2022-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.CharField(max_length=20, verbose_name='Destino')),
                ('name', models.CharField(max_length=15, verbose_name='Nome')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('date_init', models.DateField(verbose_name='Data Inicial')),
                ('date_final', models.DateField(verbose_name='Data Final')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativar')),
            ],
        ),
    ]
