# Generated by Django 4.0 on 2021-12-21 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cel_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Rede Social'),
            preserve_default=False,
        ),
    ]
