# Generated by Django 4.0 on 2021-12-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='option',
            field=models.CharField(max_length=8, verbose_name='Opção'),
        ),
    ]
