# Generated by Django 3.2.10 on 2022-03-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceselect', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Validity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4, verbose_name='Ano')),
                ('validity', models.CharField(max_length=255, verbose_name='Validade')),
                ('period', models.CharField(max_length=255, verbose_name='Período')),
                ('active', models.BooleanField(default=True, verbose_name='Vigente')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destiny.destiny')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PricesSeasonsDestinies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('price', models.CharField(max_length=9, verbose_name='Valor')),
                ('opção', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.optionsprices')),
                ('validade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.validity')),
            ],
        ),
    ]
