<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.0 on 2022-04-05 15:03
=======
# Generated by Django 3.2.10 on 2022-04-01 14:12
>>>>>>> 75c69b3841aebc4d566b673941e0f56e5b699a2b
=======
# Generated by Django 4.0 on 2022-04-05 15:25
>>>>>>> novo_transport

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validity',
<<<<<<< HEAD
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255, verbose_name='Temporada')),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4, verbose_name='Ano')),
=======
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo Agência')),
                ('sell', models.BooleanField(default=False, verbose_name='Ativo Venda')),
            ],
            options={
                'verbose_name': 'Vigência',
                'verbose_name_plural': 'Vigências',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo Agência')),
                ('sell', models.BooleanField(default=False, verbose_name='Ativo Venda')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destiny.destiny')),
                ('validity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.validity')),
>>>>>>> 75c69b3841aebc4d566b673941e0f56e5b699a2b
=======
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4, verbose_name='Ano')),
                ('is_active_company', models.BooleanField(default=False, verbose_name='Ativo Agência')),
                ('is_active_sell', models.BooleanField(default=False, verbose_name='Ativo Vendas')),
            ],
            options={
                'verbose_name': 'Vigência',
                'verbose_name_plural': 'Vigências',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('active_company', models.BooleanField(default=False, verbose_name='Ativo Agência')),
                ('active_sell', models.BooleanField(default=False, verbose_name='Ativo Venda')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destiny.destiny', verbose_name='Destino')),
                ('validity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.validity', verbose_name='Vigência')),
>>>>>>> novo_transport
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='PeriodSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('date_start', models.DateField(verbose_name='Data Inicial')),
                ('date_end', models.DateField(verbose_name='Data Final')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season')),
            ],
            options={
                'verbose_name': 'Descrição Temporada',
                'verbose_name_plural': 'Descrição Temporadas',
                'ordering': ['-date_start'],
=======
=======
>>>>>>> novo_transport
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('date_start', models.DateField(verbose_name='Data Início')),
                ('date_end', models.DateField(verbose_name='Data Fim')),
<<<<<<< HEAD
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season')),
=======
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season', verbose_name='Temporada')),
>>>>>>> novo_transport
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
<<<<<<< HEAD
>>>>>>> 75c69b3841aebc4d566b673941e0f56e5b699a2b
=======
>>>>>>> novo_transport
            },
        ),
    ]
