# Generated by Django 3.2.10 on 2022-03-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricesseasonsdestinies',
            old_name='opção',
            new_name='opcao',
        ),
        migrations.RenameField(
            model_name='validity',
            old_name='destiny',
            new_name='destino',
        ),
    ]
