# Generated by Django 3.2.10 on 2022-03-31 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo Agência'),
        ),
        migrations.AddField(
            model_name='season',
            name='sell',
            field=models.BooleanField(default=False, verbose_name='Ativo Venda'),
        ),
        migrations.AlterField(
            model_name='season',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.validity'),
        ),
    ]
