# Generated by Django 4.0.3 on 2022-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(choices=[('2026', '2026'), ('2025', '2025'), ('2022', '2022'), ('2024', '2024'), ('2027', '2027'), ('2023', '2023'), ('2030', '2030'), ('2029', '2029'), ('2028', '2028')], max_length=4),
        ),
    ]
