# Generated by Django 4.0.3 on 2022-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_alter_season_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.AlterField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Ano'),
        ),
    ]
