# Generated by Django 3.2.10 on 2022-03-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_auto_20220331_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('date_start', models.DateField(verbose_name='Data Início')),
                ('date_end', models.DateField(verbose_name='Data Fim')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.RemoveField(
            model_name='pricesseasonsdestinies',
            name='opcao',
        ),
        migrations.RemoveField(
            model_name='pricesseasonsdestinies',
            name='validade',
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='OptionsPrices',
        ),
        migrations.DeleteModel(
            name='PricesSeasonsDestinies',
        ),
        migrations.AddField(
            model_name='period',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season'),
        ),
    ]
