# Generated by Django 4.0.3 on 2022-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_alter_season_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validity',
            name='year',
            field=models.CharField(max_length=4, unique=True, verbose_name='Ano'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name_event', 'date_init', 'date_fin')},
        ),
    ]
