# Generated by Django 4.0.3 on 2022-03-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_alter_season_options_alter_season_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2022', '2022'), ('2027', '2027'), ('2023', '2023'), ('2025', '2025'), ('2026', '2026'), ('2030', '2030'), ('2029', '2029'), ('2028', '2028')], max_length=4, verbose_name='Ano'),
        ),
    ]
