# Generated by Django 4.0.3 on 2022-08-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_alter_validity_year_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
    ]
