# Generated by Django 4.0.3 on 2022-08-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_alter_season_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
    ]
