# Generated by Django 4.0.3 on 2022-03-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_alter_season_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='active',
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=4, verbose_name='Ano'),
        ),
        migrations.CreateModel(
            name='PeriodSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Data Inicial')),
                ('date_end', models.DateField(verbose_name='Data Final')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season')),
            ],
            options={
                'verbose_name': 'Descrição Temporada',
                'verbose_name_plural': 'Descrição Temporadas',
                'ordering': ['-date_start'],
            },
        ),
    ]
