# Generated by Django 4.0 on 2022-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('document_number', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('document_image', models.ImageField(blank=True, upload_to='documentos/')),
                ('street', models.CharField(max_length=200, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=30, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('postal_code', models.CharField(max_length=11, null=True, verbose_name='CEP')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
