# Generated by Django 3.2.10 on 2022-03-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
