# Generated by Django 4.0.3 on 2022-03-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=100, verbose_name='CEP')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.state'),
        ),
    ]
