# Generated by Django 4.0.3 on 2022-07-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydestinies',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='destiny.destiny', verbose_name='Destino'),
        ),
    ]
