# Generated by Django 3.2.10 on 2022-03-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='social_media',
            new_name='socmedia',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='cel_phone',
        ),
        migrations.AddField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
