# Generated by Django 3.2.10 on 2022-03-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
        ('company', '0003_auto_20220316_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydestiny',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destiny.destiny'),
        ),
    ]
