# Generated by Django 3.2.10 on 2022-03-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
        ('company', '0004_alter_companydestiny_destiny'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDestiny',
            new_name='CompanyDestinies',
        ),
    ]
