# Generated by Django 4.0 on 2022-04-05 02:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Categoria')),
                ('slug', models.SlugField(max_length=250)),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoriesPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Categoria PAX')),
            ],
            options={
                'verbose_name': 'Categoria PAX',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='produtos/%Y', verbose_name='Imagem do produto')),
                ('trip_description', models.TextField(blank=True, verbose_name='Descrição do passeio')),
                ('short_description', models.TextField(blank=True, verbose_name='Descrição curta')),
                ('politic', models.CharField(max_length=255, verbose_name='Política de CHD')),
                ('trip_duration', models.CharField(max_length=255, verbose_name='Duração do passeio')),
                ('travel_time', models.CharField(max_length=255, verbose_name='Tempo de percurso')),
                ('travel_time_untoplace', models.CharField(max_length=255, verbose_name='Tempo de percurso até o local do passeio')),
                ('ride_distance', models.CharField(max_length=255, verbose_name='Distância do passeio')),
                ('limit_load', models.CharField(max_length=255, verbose_name='Limite de carga por passeio ou guia')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão paga pelo fornecedor')),
                ('tour_notes', models.TextField(blank=True, verbose_name='Notas do passeio')),
                ('featured_image', models.FileField(upload_to='files/', verbose_name='Imagem de destaque para o site')),
                ('seo', models.CharField(max_length=155, verbose_name='Dados para SEO')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Descrição')),
                ('description_BTMS', tinymce.models.HTMLField(max_length=300, verbose_name='Vínculo ao sistema BTMS e Voucher Digital')),
                ('btms', models.CharField(max_length=300, verbose_name='Codigo BTMS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.categories', verbose_name='Categoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Passeio',
                'verbose_name_plural': 'Passeios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripSeasonPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=9, verbose_name='Preço')),
                ('cadpax', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.categoriespax', verbose_name='Cadastro PAX')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season', verbose_name='Temporada')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.trip', verbose_name='Passeio')),
            ],
            options={
                'verbose_name': 'Preço Temporada de Passeio',
                'ordering': ['trip'],
            },
        ),
    ]
