# Generated by Django 3.2.10 on 2022-03-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Categoria')),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='produtos/%Y', verbose_name='Imagem do produto')),
                ('trip_description', models.TextField(blank=True, verbose_name='Descrição do passeio')),
                ('short_description', models.TextField(blank=True, verbose_name='Descrição curta')),
                ('politic', models.CharField(max_length=255, verbose_name='Política de CHD')),
                ('trip_duration', models.CharField(max_length=255, verbose_name='Duração do passeio')),
                ('travel_time', models.CharField(max_length=255, verbose_name='Tempo de percurso')),
                ('travel_time_untoplace', models.CharField(max_length=255, verbose_name='Tempo de percurso até o local do passeio')),
                ('ride_distance', models.CharField(max_length=255, verbose_name='Distância do passeio')),
                ('limit_load', models.CharField(max_length=255, verbose_name='Limite de carga por passeio ou guia')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão paga pelo fornecedor')),
                ('tour_notes', models.TextField(blank=True, verbose_name='Descrição do passeio')),
                ('featured_image', models.FileField(upload_to='files/', verbose_name='Imagem de destaque para o site')),
                ('seo', models.CharField(max_length=155, verbose_name='Dados para SEO')),
                ('title', models.CharField(max_length=150, verbose_name='Títilo')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('description_BTMS', models.CharField(max_length=300, verbose_name='Vínculo ao sistema BTMS e Voucher Digital')),
                ('btms', models.CharField(max_length=300, verbose_name='Codigo BTMS')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.categories')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Passeio',
                'verbose_name_plural': 'Passeios',
                'ordering': ['name'],
            },
        ),
    ]
