# Generated by Django 4.0.3 on 2022-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='catpax',
            field=models.ManyToManyField(through='trip.ActivityCatPax', to='trip.categorypax', verbose_name='Categoria PAX'),
        ),
    ]
