# Generated by Django 4.0.3 on 2022-05-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripcadpaxtrip',
            unique_together={('trip', 'cadpax')},
        ),
    ]
