# Generated by Django 4.0 on 2022-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='catpax',
            field=models.ManyToManyField(blank=True, through='trip.ActivityCatPax', to='trip.CategoryPax', verbose_name='Categoria PAX'),
        ),
    ]
