# Generated by Django 4.0.3 on 2022-04-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcategory',
            name='slug',
        ),
    ]
