# Generated by Django 3.2.10 on 2022-02-27 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description_BTMS',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Vínculo ao sistema BTMS e Voucher Digital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
    ]
