# Generated by Django 4.0.3 on 2022-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='provider',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='trip',
            name='tour_notes',
            field=models.TextField(blank=True, verbose_name='Notas do passeio'),
        ),
    ]
