# Generated by Django 4.0.3 on 2022-04-16 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripprice',
            name='season',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Temporada'),
            preserve_default=False,
        ),
    ]
