# Generated by Django 4.0.3 on 2022-05-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcadpaxtrip',
            name='trip_slug',
        ),
    ]
