# Generated by Django 4.0.3 on 2022-04-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydestinies', verbose_name='Destino'),
        ),
    ]
