# Generated by Django 4.0.3 on 2022-07-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Atividade do Passeio', 'verbose_name_plural': 'Atividades do Passeio'},
        ),
        migrations.AlterModelOptions(
            name='activityprice',
            options={'verbose_name': 'Preço da atividade', 'verbose_name_plural': 'Preços das atividades'},
        ),
    ]
