# Generated by Django 3.2.10 on 2022-04-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_auto_20220401_1130'),
        ('company', '0002_auto_20220401_1130'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.categories', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tripseasonprices',
            name='cadpax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.categoriespax', verbose_name='Cadastro PAX'),
        ),
        migrations.AlterField(
            model_name='tripseasonprices',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.trip', verbose_name='Passeio'),
        ),
        migrations.AlterField(
            model_name='tripseasonprices',
            name='validity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.validity', verbose_name='Vigência'),
        ),
    ]
