# Generated by Django 3.2.10 on 2022-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='limit_load',
            field=models.IntegerField(verbose_name='Limite de carga por passeio ou guia(Nº de pessoas)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='politic',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=2, verbose_name='Política de CHD'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ride_distance',
            field=models.CharField(max_length=255, verbose_name='Distância do passeio (Km)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_duration',
            field=models.TimeField(verbose_name='Duração do passeio'),
        ),
    ]
