# Generated by Django 4.0.3 on 2022-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_trip_destiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cadpax',
        ),
        migrations.AddField(
            model_name='trip',
            name='cadpax',
            field=models.ManyToManyField(to='trip.tripcategorypax', verbose_name='Categoria PAX'),
        ),
    ]
