# Generated by Django 4.0.3 on 2022-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_activity_options_alter_activityprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='atividade/%mmm-%Y', verbose_name='Imagem da atividade'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, upload_to='passeio/%Y', verbose_name='Imagem do produto'),
        ),
    ]
