# Generated by Django 4.0.3 on 2022-05-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_remove_tripcadpaxtrip_trip_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcadpaxtrip',
            name='cadpax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadpax_passeio', to='trip.tripcategorypax'),
        ),
        migrations.AlterField(
            model_name='tripcadpaxtrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadpax_passeio', to='trip.trip'),
        ),
    ]
