# Generated by Django 4.0.3 on 2022-06-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_rename_activity_activitycatpax_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='cadpax',
            new_name='catpax',
        ),
        migrations.RenameField(
            model_name='activitycatpax',
            old_name='cadpax',
            new_name='catpax',
        ),
        migrations.RenameField(
            model_name='activityprice',
            old_name='cadpax',
            new_name='catpax',
        ),
    ]
