# Generated by Django 4.0.3 on 2022-06-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_trip_category_alter_trip_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcadpaxtrip',
            name='cadpax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripcategorypax'),
        ),
        migrations.AlterField(
            model_name='tripcadpaxtrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip'),
        ),
    ]
