# Generated by Django 4.0.3 on 2022-06-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('trip', '0003_rename_cadpax_activity_catpax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycatpax',
            name='catpax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.categorypax'),
        ),
        migrations.AlterField(
            model_name='activityprice',
            name='catpax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.categorypax', verbose_name='Categoria PAX'),
        ),
        migrations.AlterField(
            model_name='activityprice',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season', verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.tripcategory', verbose_name='Categoria'),
        ),
    ]
