# Generated by Django 4.0.3 on 2022-07-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_activity_image_alter_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='atividade/%Y', verbose_name='Imagem da atividade'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripcategory', verbose_name='Categoria'),
        ),
    ]
