# Generated by Django 4.0.3 on 2022-04-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_rename_tripseasonprices_tripprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCategoryPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Categoria PAX')),
            ],
        ),
        migrations.AlterField(
            model_name='tripprice',
            name='cadpax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trip.tripcategorypax', verbose_name='Cadastro PAX'),
        ),
    ]
