# Generated by Django 4.0.3 on 2022-05-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
        ('trip', '0003_remove_trip_cadpax_trip_cadpax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cadpax',
            field=models.ManyToManyField(to='trip.tripcategorypax'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.destiny', verbose_name='Destino'),
        ),
    ]
