# Generated by Django 4.0.3 on 2022-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_tripcategorypax_alter_tripprice_cadpax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=5, null=True, verbose_name='Comissão paga pelo fornecedor (%)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='limit_load',
            field=models.CharField(default='6', max_length=255, verbose_name='Limite de carga por passeio ou guia (Nº de pessoas)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(default='teste', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ride_distance',
            field=models.CharField(default='1', max_length=255, verbose_name='Distância do passeio (Km)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='short_description',
            field=models.TextField(blank=True, default='teste', verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tour_notes',
            field=models.TextField(blank=True, default='teste', verbose_name='Notas do passeio'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_time',
            field=models.CharField(default='00:00', max_length=255, verbose_name='Tempo de percurso (hrs)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_time_untoplace',
            field=models.CharField(default='00:00', max_length=255, verbose_name='Tempo de percurso até o local do passeio (hrs)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_description',
            field=models.TextField(blank=True, default='teste', verbose_name='Descrição do passeio'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_duration',
            field=models.CharField(default='1', max_length=255, verbose_name='Duração do passeio (hrs)'),
        ),
    ]
