# Generated by Django 4.0.3 on 2022-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_trip_cadpax_alter_trip_destiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='company',
        ),
        migrations.AlterField(
            model_name='trip',
            name='cadpax',
            field=models.ManyToManyField(blank=True, null=True, to='trip.tripcategorypax'),
        ),
    ]
