# Generated by Django 4.0.3 on 2022-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_remove_trip_company_alter_trip_cadpax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cadpax',
            field=models.ManyToManyField(blank=True, to='trip.tripcategorypax'),
        ),
    ]
