# Generated by Django 4.0 on 2022-04-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.CharField(max_length=255, verbose_name='Destino')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ('destiny',),
            },
        ),
        migrations.CreateModel(
            name='DestinySeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destiny.destiny')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season')),
            ],
            options={
                'verbose_name': 'Destino Temporada',
                'verbose_name_plural': 'Destino Temporadas',
                'ordering': ('-season',),
            },
        ),
    ]
