# Generated by Django 4.0.3 on 2022-03-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_alter_season_year'),
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinySeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=150, verbose_name='Período')),
                ('date_start', models.DateField(verbose_name='Início')),
                ('date_end', models.DateField(verbose_name='Fim')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destiny.destiny')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season')),
            ],
            options={
                'verbose_name': 'Destino Temporada',
                'verbose_name_plural': 'Destino Temporadas',
                'ordering': ('-season',),
            },
        ),
    ]
