# Generated by Django 4.0.3 on 2022-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destiny',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='destiny',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='destiny',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Destino'),
        ),
    ]
