# Generated by Django 4.0.3 on 2022-06-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destiny',
            unique_together={('name', 'city', 'state')},
        ),
    ]
