# Generated by Django 4.0.3 on 2022-04-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
