# Generated by Django 3.2.10 on 2022-03-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0002_delete_destinyseasons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinyPeriodSeasons',
        ),
    ]
