# Generated by Django 3.2.10 on 2021-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='option',
            field=models.CharField(choices=[('1', 'Agência'), ('2', 'Cliente'), ('3', 'Parceiro')], max_length=8, verbose_name='Opção'),
        ),
    ]
