# Generated by Django 3.2.10 on 2021-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=30, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=11, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=200, null=True, verbose_name='Endereço'),
        ),
    ]
