# Generated by Django 4.0 on 2022-02-01 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='imagem/% d/% m/% Y/', verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
