# Generated by Django 4.0 on 2022-02-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_document_image_alter_user_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_image',
            field=models.ImageField(blank=True, upload_to='docs/% Y/% m/% d/'),
        ),
    ]
