# Generated by Django 4.0 on 2022-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_image',
            field=models.ImageField(blank=True, upload_to='documentos/'),
        ),
    ]
