# Generated by Django 4.0 on 2022-04-02 21:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=255, verbose_name='Categoria PAX')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stretch', models.CharField(max_length=255, unique=True, verbose_name='Trecho')),
                ('hits', models.PositiveIntegerField(verbose_name='Acessos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativar')),
                ('document', models.FileField(upload_to='files/', verbose_name='Documento')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ('stretch',),
            },
        ),
        migrations.CreateModel(
            name='Transport_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=255, verbose_name='Tipo de transporte')),
            ],
        ),
        migrations.CreateModel(
            name='TransportPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=9, verbose_name='Preço')),
                ('cadpax', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.categoriespax', verbose_name='Cadastro PAX')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='season.season', verbose_name='Temporada')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.transport', verbose_name='Transporte')),
            ],
        ),
        migrations.AddField(
            model_name='categoriespax',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.transport_type', verbose_name='Tipo de Transporte'),
        ),
    ]
