# Generated by Django 4.0.3 on 2022-04-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesPax',
            new_name='TransportCategoryPax',
        ),
        migrations.AlterModelOptions(
            name='transportcategorypax',
            options={'verbose_name': 'Categoria PAX de Transporte', 'verbose_name_plural': 'Categorias PAX de Transporte'},
        ),
    ]
